language: node_js
node_js:
  - '6'
  cache:
  directories:
  - node_modules
script:
  - npm test
before_install:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_f9d49e660b56_key -iv $encrypted_f9d49e660b56_iv -in .env.enc -out .env -d || true'
env:
  global:
  - CF_APP=personal-wealth-portoflio-mgt-bot
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=IBM
  - CF_SPACE=dev
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: master
    repo: IBM/personal-wealth-portoflio-mgt-bot
  skip_cleanup: true